import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import Script from "next/script";
import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "./providers";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Script src="https://telegram.org/js/telegram-web-app.js"></Script>
        <Providers>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
