import { Box, Container } from "@radix-ui/themes";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container py="4" size="1">
      <Box
        style={{
          background: "var(--gray-a3)",
          borderRadius: "var(--radius-3)",
        }}
        p="3"
      >
        {children}
      </Box>
    </Container>
  );
}
